version: "3.8"

services:
  database:
    image: postgres
    container_name: database
    restart: on-failure
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=operacional
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
