INSERT INTO DEPARTAMENTOS (COD_DPTO,NOME_DPTO) VALUES (1,'DEP1');
INSERT INTO DEPARTAMENTOS (COD_DPTO,NOME_DPTO) VALUES (2,'DEP2');
INSERT INTO DEPARTAMENTOS (COD_DPTO,NOME_DPTO) VALUES (3,'DEP3');
INSERT INTO DEPARTAMENTOS (COD_DPTO,NOME_DPTO) VALUES (4,'DEP4');
INSERT INTO DEPARTAMENTOS (COD_DPTO,NOME_DPTO) VALUES (5,'DEP5');

INSERT INTO CURSOS
SELECT COD_CURSO, NOM_CURSO, 2
FROM ACADEMICO.CURSOS WHERE MOD (COD_CURSO, 2) = 0;

INSERT INTO CURSOS
SELECT COD_CURSO, NOM_CURSO, 1
FROM ACADEMICO.CURSOS WHERE MOD (COD_CURSO, 2) != 0;

INSERT INTO DISCIPLINAS
SELECT COD_DISC, NOM_DISC, HORAS_OBRIG
FROM ACADEMICO.DISCIPLINAS;

INSERT INTO ALUNOS
SELECT MAT_ALU, NOM_ALU, DAT_NASC, COD_CURSO, 'F'
FROM ACADEMICO.ALUNOS WHERE MOD (MAT_ALU, 2) = 0;

INSERT INTO ALUNOS
SELECT MAT_ALU, NOM_ALU, DAT_NASC, COD_CURSO, 'T'
FROM ACADEMICO.ALUNOS WHERE MOD (MAT_ALU, 2) != 0;

INSERT INTO MATRIZES_CURSOS
SELECT COD_CURSO, COD_DISC, PERIODO
FROM ACADEMICO.MATRIZES WHERE COD_DISC = ACADEMICO.MATRIZES.COD_DISC;

delete from ACADEMICO.MATRICULAS a
where rowid > (select min(rowid) from ACADEMICO.MATRICULAS b
where b.MAT_ALU=a.MAT_ALU
and b.MAT_ALU=a.MAT_ALU);

INSERT INTO MATRICULAS
SELECT SEMESTRE, ACADEMICO.MATRICULAS.MAT_ALU, COD_DISC, ROUND(DBMS_RANDOM.VALUE(1,5)), ROUND(DBMS_RANDOM.VALUE(1,20)), 'A' FROM ACADEMICO.MATRICULAS WHERE MOD (MAT_ALU, 2) = 0;